/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_dlab_ppganalyzer_MainActivity_Preview */

#ifndef _Included_edu_mit_dlab_ppganalyzer_MainActivity_Preview
#define _Included_edu_mit_dlab_ppganalyzer_MainActivity_Preview
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
