/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_dlab_ppganalyzer_ImageHandler */

#ifndef _Included_edu_mit_dlab_ppganalyzer_ImageHandler
#define _Included_edu_mit_dlab_ppganalyzer_ImageHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_mit_dlab_ppganalyzer_ImageHandler_MIN_PRIORITY
#define edu_mit_dlab_ppganalyzer_ImageHandler_MIN_PRIORITY 1L
#undef edu_mit_dlab_ppganalyzer_ImageHandler_NORM_PRIORITY
#define edu_mit_dlab_ppganalyzer_ImageHandler_NORM_PRIORITY 5L
#undef edu_mit_dlab_ppganalyzer_ImageHandler_MAX_PRIORITY
#define edu_mit_dlab_ppganalyzer_ImageHandler_MAX_PRIORITY 10L
#undef edu_mit_dlab_ppganalyzer_ImageHandler_TIME_STEP
#define edu_mit_dlab_ppganalyzer_ImageHandler_TIME_STEP 20i64
#undef edu_mit_dlab_ppganalyzer_ImageHandler_SAMPLING_FREQUENCY
#define edu_mit_dlab_ppganalyzer_ImageHandler_SAMPLING_FREQUENCY 50.0
/*
 * Class:     edu_mit_dlab_ppganalyzer_ImageHandler
 * Method:    process
 * Signature: ([BII)[I
 */
JNIEXPORT jintArray JNICALL Java_edu_mit_dlab_ppganalyzer_ImageHandler_process
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     edu_mit_dlab_ppganalyzer_ImageHandler
 * Method:    setRadius
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_edu_mit_dlab_ppganalyzer_ImageHandler_setRadius
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     edu_mit_dlab_ppganalyzer_ImageHandler
 * Method:    getRadius
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_edu_mit_dlab_ppganalyzer_ImageHandler_getRadius
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
