/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_dlab_ppganalyzer_MainActivity */

#ifndef _Included_edu_mit_dlab_ppganalyzer_MainActivity
#define _Included_edu_mit_dlab_ppganalyzer_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_mit_dlab_ppganalyzer_MainActivity_SETTINGS
#define edu_mit_dlab_ppganalyzer_MainActivity_SETTINGS 1L
#ifdef __cplusplus
}
#endif
#endif
