/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_dlab_ppganalyzer_GraphViewFinal */

#ifndef _Included_edu_mit_dlab_ppganalyzer_GraphViewFinal
#define _Included_edu_mit_dlab_ppganalyzer_GraphViewFinal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_dlab_ppganalyzer_GraphViewFinal
 * Method:    fft
 * Signature: ([I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_mit_dlab_ppganalyzer_GraphViewFinal_fft
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     edu_mit_dlab_ppganalyzer_GraphViewFinal
 * Method:    firFilter
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_edu_mit_dlab_ppganalyzer_GraphViewFinal_firFilter
  (JNIEnv *, jobject, jintArray);
#ifdef __cplusplus
}
#endif
#endif
