/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_dlab_ppganalyzer_MainActivity_snapshot */

#ifndef _Included_edu_mit_dlab_ppganalyzer_MainActivity_snapshot
#define _Included_edu_mit_dlab_ppganalyzer_MainActivity_snapshot
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
